// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA319msdaUCvXlji62xpDODO3L5jaUnl74',
    appId: '1:327251677878:web:f6e617f0163f4460f0cc17',
    messagingSenderId: '327251677878',
    projectId: 'wash-5bcf7',
    authDomain: 'wash-5bcf7.firebaseapp.com',
    storageBucket: 'wash-5bcf7.firebasestorage.app',
    measurementId: 'G-RR0N3PGEKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1iN4yaeSfz6eS2jRQ0AwCn7XjN3bJlE',
    appId: '1:327251677878:android:84f7926dc624cf15f0cc17',
    messagingSenderId: '327251677878',
    projectId: 'wash-5bcf7',
    storageBucket: 'wash-5bcf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgz9vJsKaLQuB5GDeujT9_O-5GB10EDag',
    appId: '1:327251677878:ios:ea88fc10404b15eaf0cc17',
    messagingSenderId: '327251677878',
    projectId: 'wash-5bcf7',
    storageBucket: 'wash-5bcf7.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgz9vJsKaLQuB5GDeujT9_O-5GB10EDag',
    appId: '1:327251677878:ios:ea88fc10404b15eaf0cc17',
    messagingSenderId: '327251677878',
    projectId: 'wash-5bcf7',
    storageBucket: 'wash-5bcf7.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA319msdaUCvXlji62xpDODO3L5jaUnl74',
    appId: '1:327251677878:web:dc8a5f4e7900ec22f0cc17',
    messagingSenderId: '327251677878',
    projectId: 'wash-5bcf7',
    authDomain: 'wash-5bcf7.firebaseapp.com',
    storageBucket: 'wash-5bcf7.firebasestorage.app',
    measurementId: 'G-P3VNP49D9W',
  );
}
